# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='resp_national_id',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='resp_cheque',
            field=models.TextField(blank=True, null=True, verbose_name='response_cheque'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='resp_loans',
            field=models.TextField(blank=True, null=True, verbose_name='response_loans'),
        ),
    ]
