# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 09:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_auto_20160816_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='resp_cheque',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='response_cheque'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='resp_loans',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='response_loans'),
        ),
    ]
