# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('set_date', models.DateTimeField()),
                ('date_has_been_set', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Applicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام و نام خانوادگی', max_length=200)),
                ('company_name', models.CharField(help_text='نام شرکت', max_length=200)),
                ('address', models.CharField(help_text='آدرس شرکت', max_length=400)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='applicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Applicator'),
        ),
    ]
