# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['request_date']},
        ),
        migrations.AlterField(
            model_name='application',
            name='set_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='city',
            field=models.CharField(help_text='شهر', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='email',
            field=models.EmailField(help_text='آدرس ایمیل', max_length=254),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='website',
            field=models.URLField(blank=True, help_text='آدرس وبسایت شرکت'),
        ),
    ]
