# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20160806_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='set_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
