# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20160806_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicator',
            name='address',
            field=models.CharField(max_length=400, verbose_name='آدرس شرکت'),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='applicator',
            name='website',
            field=models.URLField(blank=True, verbose_name='آدرس وبسایت شرکت'),
        ),
    ]
