# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 07:19
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_num_of_requests_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_of_requests_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Requests Made'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
